guard 'rake', :task => 'parse_haml' do
	watch(%r{_source/_layouts/haml/})
end

guard 'rake', :task => 'parse_haml_pages' do
	watch(%r{_source/_layouts/pages/})
end

guard 'rake', :task => 'parse_sass' do
	watch(%r{_source/_layouts/sass/})
end